# Generated by Django 4.0.1 on 2022-03-29 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveIntegerField()),
                ('dept', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('credits', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('course_number', 'dept')},
            },
        ),
        migrations.CreateModel(
            name='GenEdReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_term', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('acp', models.CharField(max_length=30)),
                ('cs', models.CharField(max_length=30)),
                ('hum', models.CharField(max_length=30)),
                ('nat', models.CharField(max_length=30)),
                ('sbs', models.CharField(max_length=30)),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_course_n', to='course_exp.course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen_dept', to='course_exp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_exp.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('professors', models.CharField(max_length=500)),
                ('avg_gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('course_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_course_n', to='course_exp.course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_dept', to='course_exp.course')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_exp.professor')),
                ('year_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_exp.genedreq')),
            ],
            options={
                'unique_together': {('course_number', 'dept')},
            },
        ),
    ]
