# Generated by Django 4.0.1 on 2022-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_exp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='avg_gpa',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='userinput',
            name='course_req',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userinput',
            name='fav_professor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userinput',
            name='interests',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='avg_gpa',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
    ]
