# Generated by Django 4.0.1 on 2022-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_exp', '0002_userinput_avg_gpa_userinput_course_req_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='interests',
            field=models.CharField(default='0.0.0000986320.8956230.9856230.8456230.22288888', max_length=255),
        ),
    ]
